-- 코드를 입력하세요
# SELECT * FROM FIRST_HALF
# WHERE TOTAL_ORDER >= 3000

# SELECT * FROM ICECREAM_INFO
# WHERE INGREDIENT_TYPE = 'fruit_based'

SELECT a.FLAVOR
FROM FIRST_HALF a JOIN ICECREAM_INFO b ON a.FLAVOR = b.FLAVOR
WHERE a.TOTAL_ORDER > 3000
and b.INGREDIENT_TYPE = 'fruit_based'
ORDER BY a.TOTAL_ORDER DESC